spring:
  application:
    name: clinic

  datasource:
    url: jdbc:mysql://localhost:3306/dental_clinic
    username: root
    password: Nicolas200!

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

server:
  port: 8080