spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dental_clinic}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:change-me-root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/dev-data
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    baseline-version: ${FLYWAY_BASELINE_VERSION:2}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}

  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  security:
    public-docs-enabled: true
    jwt:
      secret: ${JWT_SECRET}